---
paths:
    /items/{alfInstanceId}:
        get:
        parameters:
            - in: path
            Name: alfInstanceId
            required: false
            type: string
            $ ref: '#/parameters/alfInstanceId
