openapi: "3.0.1"
info:
  title: "teleto API"
  version: "2020-11-24T05:34:25Z"
servers:
- url: "https://ttnxcty7yc.execute-api.us-east-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/stage"
paths:
  /topics:
    get:
      parameters:
      - name: "grouphash"
        in: "query"
        schema:
          type: "string"
      - name: "random"
        in: "query"
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getTopics"
    options:
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /members:
    get:
      parameters:
      - name: "grouphash"
        in: "query"
        schema:
          type: "string"
      - name: "random"
        in: "query"
        schema:
          type: "string"
      responses:
        400:
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getMembers"
            application/json(全取得):
              schema:
                $ref: "#/components/schemas/getAllMembers"
    post:
      parameters:
      - name: "grouphash"
        in: "query"
        schema:
          type: "string"
      responses:
        401:
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
        402:
          description: "402 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
        201:
          description: "201 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/postMembers"
    delete:
      parameters:
      - name: "memberhash"
        in: "query"
        schema:
          type: "string"
      - name: "grouphash"
        in: "query"
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/deleteMember"
        402:
          description: "402 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
    options:
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
    getTopics:
      title: "getTopicsModel"
      type: "object"
      properties:
        value:
          type: "string"
    getAllMembers:
      title: "getAllMembersModel"
      type: "object"
      properties:
        members:
          type: "array"
          items:
            type: "object"
            properties:
              grouphash:
                type: "string"
              memberhash:
                type: "string"
              membername:
                type: "string"
    deleteMember:
      title: "grouphashModel"
      type: "object"
      properties:
        memberhash:
          type: "string"
    postMembers:
      title: "postMembersModel"
      type: "object"
      properties:
        grouphash:
          type: "string"
    getMembers:
      title: "getMembersModel"
      type: "object"
      properties:
        value:
          type: "string"
