---
swagger: "2.0"
info:
  version: "2020-11-23T07:48:34Z"
  title: "teleto API"
host: "ttnxcty7yc.execute-api.us-east-2.amazonaws.com"
basePath: "/stage"
schemes:
- "https"
paths:
  /members:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "grouphash"
        in: "query"
        required: false
        type: "string"
      - name: "random"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/getMembers"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    post:
      parameters:
        - in: body
          name: members
          schema:
            type: object
            properties:
              members:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
      produces:
      - "application/json"
      responses:
        201:
          description: "201 response"
          schema:
            $ref: "#/definitions/postMembers"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        401:
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        402:
          description: "402 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /topics:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "grouphash"
        in: "query"
        required: false
        type: "string"
      - name: "random"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/getTopics"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
  getTopics:
    type: "object"
    properties:
      value:
        type: "string"
    title: "getTopicsModel"
  postMembers:
    type: "object"
    properties:
      grouphash:
        type: "string"
    title: "grouphashModel"
  getMembers:
    type: "object"
    properties:
      value:
        type: "string"
    title: "getMemberstModel"
