name: BackEnd-dev CI

on:
  push:
    branches:
      - dev
    pull_request:
      - dev

jobs:
  aws_cdk:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: Setup dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Unit tests
        if: contains(github.event_name, 'pull_request')
        run: npm run test:app

      - name: CDK Diff Check
        if: contains(github.event_name, 'pull_request')
        run: npm run cdk:diff
        env:
          AWS_DEFAULT_REGION: "us-east-2"
          AWS_ACCESS_KEY_ID: "${{ secrets.TELETO_BACKEND_AWS_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.TELETO_BACKEND_AWS_KEY }}"

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: npm run cdk:deploy
        env:
          AWS_DEFAULT_REGION: "us-east-2"
          AWS_ACCESS_KEY_ID: "${{ secrets.TELETO_BACKEND_AWS_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.TELETO_BACKEND_AWS_KEY }}"
