name: BackEnd-dev CI

on:
  push:
    branches:
      - dev
    pull_request:
      - dev

jobs:
  aws_cdk:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules.
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install Dependencies
        run: yarn install

      - name: Unit tests
        # if: contains(github.event_name, 'pull_request')
        run: yarn test

      - name: CDK Diff Check
        # if: contains(github.event_name, 'pull_request')
        run: yarn cdk:diff
        env:
          AWS_DEFAULT_REGION: "us-east-2"
          AWS_ACCESS_KEY_ID: "${{ secrets.TELETO_BACKEND_AWS_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.TELETO_BACKEND_AWS_KEY }}"

      # - name: CDK Deploy
      #   if: contains(github.event_name, 'push')
      #   run: yarn cdk:deploy
      #   env:
      #     AWS_DEFAULT_REGION: "us-east-2"
      #     AWS_ACCESS_KEY_ID: "${{ secrets.TELETO_BACKEND_AWS_ID }}"
      #     AWS_SECRET_ACCESS_KEY: "${{ secrets.TELETO_BACKEND_AWS_KEY }}"
